import { default as EventDispatcher } from '../events/EventDispatcher';
import { default as uuid } from '../util/uuid';
import $ from 'jquery';

/**
 * Base type for all UI elements
 * @class lavaca.ui.Widget
 * @extends lavaca.events.EventDispatcher
 *
 * @constructor
 *
 * @param {jQuery} el  The DOM element that is the root of the widget
 */
var Widget = EventDispatcher.extend(function (el){
  EventDispatcher.call(this);
  /**
   * The DOM element that is the root of the widget
   * @property {jQuery} el
   * @default null
   */
  this.el = el = $(el);
  var id = el.attr('id');
  if (!id) {
    id = 'widget-' + uuid();
  }
  /**
   * The el's ID
   * @property {String} id
   * @default (Autogenerated)
   */
  this.id = id;
});

export default Widget;